version: 2.1
jobs:
  build:
    docker: 
      - image: circleci/node:4.8.2 # the primary container, where your job's commands are run
    steps:
      - checkout # check out the code in the project directory

  # These commands are triggered only after a successful (green) build.
  deploy:
   steps:
     - add_ssh_keys:
       fingerprints:
         - "7b:41:0e:0d:60:1d:e8:d9:a0:38:fa:6f:24:c0:79:73"
     - run:
       name: Deploy over SSH
       command: ssh $SSH_USER@$SSH_HOST 'cd /opt/bitnami/apache2/htdocs && git pull origin master'     

workflows:
  version: 2.1
  build-and-deploy:
    jobs:
      - build
      - deploy:
        requires:
          - build
        filters:
          branches:
            only: master          