defaults: &defaults
  docker:
    - image: circleci/node:4.8.2

version: 2.1
jobs:     
  deploy_site:
    <<:***REMOVED***defaults
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "bd:b6:18:31:16:ba:a9:4b:16:1b:e4:4e:b9:60:06:b0"
      - run:
          name: Deploy to Server
          command: sudo scp -r web120***REMOVED*** $SSH_USER@$SSH_HOST:/opt/bitnami/apache2/htdocs/
          #command: scp -r web120***REMOVED*** $SSH_USER@$SSH_HOST:/opt/bitnami/apache2/htdocs/     
          
workflows:
  version: 2.1
  workflow:
    jobs:
      - deploy_site
   