defaults: &defaults
  docker:
    - image: circleci/node:4.8.2

version: 2.1
jobs:     
  deploy_site:
    <<:***REMOVED***defaults
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "cf:b7:c5:9c:ed:12:7a:30:99:10:66:82:e9:22:68:d2"
      - run:
          name: Deploy to Server
          command: sudo scp -r web120***REMOVED*** $SSH_USER@$SSH_HOST:/opt/bitnami/apache2/htdocs/
          #command: scp -r web120***REMOVED*** $SSH_USER@$SSH_HOST:/opt/bitnami/apache2/htdocs/     
          
workflows:
  version: 2.1
  workflow:
    jobs:
      - deploy_site
   